### ISSUE TITLE
Chat not found

### ISSUE THREAD

**Issue by inozemtsev-roman** [TON-Punks/ton-nft-verify-bot#1]
Hi! In the application logs, the bot works up to the get_privileges item. The address is correct, Example: -705168423

Such an error:

logs:
```bash
2022-07-28T10:29:34.472230+00:00 app[web.1]: ERROR:aiohttp.server:Error handling request
2022-07-28T10:29:34.472239+00:00 app[web.1]: Traceback (most recent call last):
2022-07-28T10:29:34.472256+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
2022-07-28T10:29:34.472257+00:00 app[web.1]:     resp = await request_handler(request)
2022-07-28T10:29:34.472257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
2022-07-28T10:29:34.472257+00:00 app[web.1]:     resp = await handler(request)
2022-07-28T10:29:34.472257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py", line 954, in _iter
2022-07-28T10:29:34.472258+00:00 app[web.1]:     resp = await method()
2022-07-28T10:29:34.472258+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/dispatcher/webhook.py", line 139, in post
2022-07-28T10:29:34.472258+00:00 app[web.1]:     results = await self.process_update(update)
2022-07-28T10:29:34.472263+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/dispatcher/webhook.py", line 190, in process_update
2022-07-28T10:29:34.472264+00:00 app[web.1]:     return fut.result()
2022-07-28T10:29:34.472264+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
2022-07-28T10:29:34.472265+00:00 app[web.1]:     response = await handler_obj.handler(*args, **partial_data)
2022-07-28T10:29:34.472265+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
2022-07-28T10:29:34.472266+00:00 app[web.1]:     return await self.callback_query_handlers.notify(update.callback_query)
2022-07-28T10:29:34.472266+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
2022-07-28T10:29:34.472266+00:00 app[web.1]:     response = await handler_obj.handler(*args, **partial_data)
2022-07-28T10:29:34.472266+00:00 app[web.1]:   File "/app/main.py", line 71, in privileges
2022-07-28T10:29:34.472267+00:00 app[web.1]:     link = await bot.create_chat_invite_link(CHAT_ID, name=f'{callback_query.from_user.id}',
2022-07-28T10:29:34.472267+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/bot/bot.py", line 2037, in create_chat_invite_link
2022-07-28T10:29:34.472267+00:00 app[web.1]:     result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
2022-07-28T10:29:34.472267+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/bot/base.py", line 231, in request
2022-07-28T10:29:34.472267+00:00 app[web.1]:     return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
2022-07-28T10:29:34.472268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
2022-07-28T10:29:34.472268+00:00 app[web.1]:     return check_result(method, response.content_type, response.status, await response.text())
2022-07-28T10:29:34.472268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
2022-07-28T10:29:34.472268+00:00 app[web.1]:     exceptions.BadRequest.detect(description)
2022-07-28T10:29:34.472268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
2022-07-28T10:29:34.472268+00:00 app[web.1]:     raise err(cls.text or description)
2022-07-28T10:29:34.472269+00:00 app[web.1]: aiogram.utils.exceptions.ChatNotFound: Chat not found
2022-07-28T10:29:34.472579+00:00 app[web.1]: INFO:aiohttp.access:10.1.88.56 [28/Jul/2022:10:29:34 +0000] "POST /webhook/XXXXXXX:TTTTTTT(token change, its ok) HTTP/1.1" 500 245 "-" "-"
```

**Comment by thepaket** [comment]
> Example: -705168423

Hi! The correct form of an chat ID for Telegram bots (on your example): -100705168423

In a future update, we will add chat ID validation
